config/routes.rb
Tickets::Application.routes.draw do

  resources :settings, only: [:edit, :update]
  root to: "home#index"
  devise_for :users, controllers: { registrations: "registrations" }
  # get "/:id", to: "home#else"
  post "/submit", to: "home#submit"

end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
# -*- coding: utf-8 -*-
class HomeController < ApplicationController
  before_filter :setup_negative_captcha, only: [:index, :submit]

  def index
    @set = Setting.find_or_create_by(name: 'ticket')
  end

  def else
    redirect_to root_path
  end

  def submit
    NoticeMailer.new_callback_form(@captcha.values).deliver
    flash[:notice] = 'Спасибо за заказ, мы свяжемся с вами в ближайшее время!'
    redirect_to root_path
  end

  private

  def setup_negative_captcha
    @captcha = NegativeCaptcha.new(

      secret: ENV['SECRET_TOKEN'],
      spinner: request.remote_ip, 

      fields: [:name, :phone, :email, :utm_term],
      params: params
    )
  end
end

app/controllers/registrations_controller.rb
# -*- coding: utf-8 -*-
class RegistrationsController < Devise::RegistrationsController
  before_filter :authenticate_user!

  def new
    render text: 'forbidden'
  end

  def edit
    render action: :edit
  end

  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(users_params)
    else
      # remove the virtual current_password attribute update_without_password
      # doesn't know how to ignore it
      params[:user].delete(:current_password)
      @user.update_without_password(users_params)
    end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, bypass: true
      redirect_to edit_user_registration_path
    else
      render action: :edit
    end
  end

  private

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    # user.email != params[:user][:email] ||
    !params[:user][:password].blank?
  end


  def users_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :remember_me,
                                 :avatar, :full_name, :info_image,
                                 :my_vision, :about_me, :technique,
                                 :phone, :email_contact, :site,
                                 :vkontakte, :blog_image)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!

  def edit
    @set = Setting.find(params[:id])
    @setting = @set
  end

  def update
    @setting = Setting.find(params[:id])
    if @setting.update_attributes(setting_params)
      flash[:notice] = "Settings Save"
    else
      flash[:wrong] = "Something wrong"
    end
    redirect_to root_path
  end

  private

  def setting_params
    params.require(:setting).permit(:title, :description, :keywords,
                                    :email, :email_show, :phone_one,
                                    :phone_two, :metrika, :google,
                                    :vkgroup, :fbgroup, :phone_three)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  def keywords(page_keywords)
    content_for(:keywords) { page_keywords }
  end

  def description(page_description)
    content_for(:description) { page_description }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Twitter Bootstrap 2.3
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Home", root_path, class: 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, method: 'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'Tickets'
    %meta{name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Tickets'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %main{role: "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'Рекламные билеты в маршрутных такси Чебоксары'
    %meta{name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Tickets'}"}
    %meta{name: "keywords", content: "#{content_for?(:keywords) ? yield(:keywords) : 'билеты'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag 'http://maps.api.2gis.ru/1.0'
    = csrf_meta_tags
  %body
    .gradient1
    %main{role: "main"}
      - if user_signed_in?
        .admin-red-button
          = link_to "настройки", edit_setting_path(1)
      = yield
    %footer
      .container
        .content
          .row
            .span8
              #companyMap{ style: "width: 620px; height: 400px" }
              :javascript
                // Создаем обработчик загрузки страницы:
                DG.autoload(function() {
                  var myMap = new DG.Map('companyMap');
                  // myMap.setCenter(new DG.GeoPoint(82.9278, 55.0289), 9);
                  // @company.city.name
                  // types: ['city', 'settlement', 'district'],
                  DG.Geocoder.get("Чебоксары, Калинина, 80", {
                      limit: 1,
                      // Обработка успешного поиска
                      success: function(geocoderObjects) {
                          // Обходим циклом все полученные геообъекты
                          for(var i = 0, len = geocoderObjects.length; i < len; i++) {
                              var geocoderObject = geocoderObjects[i];
                              var centerPoint = geocoderObject.getCenterGeoPoint();
                              myMap.setCenter(new DG.GeoPoint(centerPoint.getLon(), centerPoint.getLat()), 16);

                              // Получаем маркер из геообъекта с помощью метода getMarker.
                              // Первый параметр - иконка маркера, второй параметр - функция, которая сработает при клике на маркер
                              var markerIcon = null; // иконка по умолчанию
                              var marker = geocoderObject.getMarker(
                                  markerIcon,
                                  (function(geocoderObject) {
                                      return function () {
                                          var info =  '';

                                          // Основная информация о геообъекте
                                          info += 'Type: ' + geocoderObject.getType() + '\n';
                                          info += 'Name: ' + geocoderObject.getName() + '\n';
                                          info += 'Short name: ' + geocoderObject.getShortName() + '\n';

                                          // Дополнительная информация о геообъекте
                                          var attributes = geocoderObject.getAttributes();
                                          for (var attribute in attributes) {
                                              if (attributes.hasOwnProperty(attribute)) {
                                                  info += attribute + ': ' + attributes[attribute] + '\n';
                                              }
                                          }

                                          // Географические координаты центра геообъекта
                                          var centerGeoPoint = geocoderObject.getCenterGeoPoint();
                                          info += 'Longitude: ' + centerGeoPoint.getLon() + '\n';
                                          info += 'Latitude: ' + centerGeoPoint.getLat();

                                      }
                                  })(geocoderObject) //Создаем анонимную функцию и сразу же ее вызываем
                              );

                              myMap.markers.add(marker);
                          }
                      },
                      // Обработка ошибок
                      failure: function(code, message) {
                          alert(code + ' ' + message);
                      }
                  });
                });
            .span4
              - if @set && @set.vkgroup.present?
                = @set.vkgroup.html_safe
    - if @set && @set.metrika.present?
      = @set.metrika.html_safe
    - if @set && @set.google.present?
      = @set.google.html_safe

app/views/settings/edit.html.haml
.container
  .content
    .row
      .span10.offset1
        = simple_form_for(@setting, html: { id: 'j-form-speller' }) do |f|
          = f.error_notification
          = f.input :title, label: 'Заголовок сайта', input_html: { class: "input-xxlarge" }
          = f.input :description, label: 'Описание сайта', input_html: { rows: 7, class: "input-block-level" }
          = f.input :keywords, label: 'SEO слова (через запятую)', input_html: { rows: 7, class: "input-block-level" }
          = f.input :email, label: 'Почтовый ящик для получения писем', input_html: { class: "input-xxlarge" }
          = f.input :email_show, label: 'Почтовый ящик для на странице сайта', input_html: { class: "input-xxlarge" }
          = f.input :phone_one, label: 'Первый телефон для контактов на странице сайта', input_html: { class: "input-xxlarge" }
          = f.input :phone_two, label: 'Второй телефон для контактов на странице сайта', input_html: { class: "input-xxlarge" }
          = f.input :phone_three, label: 'Третий телефон для контактов на странице сайта', input_html: { class: "input-xxlarge" }
          = f.input :metrika, label: 'Яндекс метрика на сайте', input_html: { rows: 7, class: "input-block-level" }
          = f.input :google, label: 'Гугл аналитика на сайте', input_html: { rows: 7, class: "input-block-level" }
          = f.input :vkgroup, label: 'VK Группа в низу сайта', input_html: { rows: 7, class: "input-block-level" }

          = f.button :submit, "Сохранить", class: 'btn-success'